export const HAS_ONBOARDED = 'HAS_ONBOARDED'

export const CLEAR_ALL_ERROR_MESSAGE = 'CLEAR_ALL_ERROR_MESSAGE'

export const AUTH_TYPE = 'AUTH_TYPE'

export const LOGIN = 'LOGIN'

export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGN_UP = 'SIGN_UP'

export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const LOGOUT = 'LOGOUT'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'

export const VERIFY_EMAIL = 'VERIFY_EMAIL'

export const RESEND_CODE = 'RESEND_CODE'

export const FULLSCREEN = 'FULLSCREEN'

export const GET_USER = 'GET_USER'

export const GET_USER_FAILED = 'GET_USER_FAILED'

export const GET_COURSES = 'GET_COURSES'

export const GET_COURSES_FAILED = 'GET_COURSES_FAILED'

export const GET_TESTS = 'GET_TESTS'

export const GET_TESTS_FAILED = 'GET_TESTS_FAILED'

export const POST_SCORE = 'POST_SCORE'

export const POST_SCORE_FAILED = 'POST_SCORE_FAILED'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

export const PROFILE_PICS = 'PROFILE_PICS'

export const CHANGE_CLASS = 'CHANGE_CLASS'

export const CHANGE_CLASS_FAILED = 'CHANGE_CLASS_FAILED'

export const PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL'

export const PAYMENT_FAILURE = 'PAYMENT_FAILURE'

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN'

export const MOST_VIEWED = 'MOST_VIEW'
